import React, { createContext, useContext } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (language: string) => void;
  t: (category: string, key: string, options?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = React.useState<string>(localStorage.getItem('language') || 'fr');

  React.useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const translations = {
    en,
    ar,
    fr,
  };

  const t = (category: string, key: string, options?: Record<string, string | number>): string => {
    const translation = translations[language as keyof typeof translations]?.[category]?.[key] || key;

    if (options) {
      let translatedText = translation;
      for (const optionKey in options) {
        translatedText = translatedText.replace(`{{${optionKey}}}`, String(options[optionKey]));
      }
      return translatedText;
    }

    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// English translations
const en = {
  common: {
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    name: "Name",
    code: "Code",
    quantity: "Quantity",
    price: "Price",
    taxRate: "Tax Rate",
    total: "Total",
    january: "January",
    february: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    august: "August",
    september: "September",
    october: "October",
    november: "November",
    december: "December",
    year: "Year",
    month: "Month",
    selectMonth: "Select Month",
    selectYear: "Select Year",
    distribution: "Distribution",
    logout: "Logout",
  },
  login: {
    title: "Login",
    secretCode: "Secret Code",
    enterCode: "Enter your secret code",
    loginButton: "Login",
    invalidCode: "Invalid secret code",
  },
  settings: {
    title: "Settings",
    companyName: "Company Name",
    secretCode: "Secret Code",
    minInvoiceAmount: "Min. Invoice Amount",
    maxInvoiceAmount: "Max. Invoice Amount",
    updateSettings: "Update Settings",
    settingsUpdated: "Settings updated successfully",
  },
  inventory: {
    title: "Inventory",
    cylinderType: "Cylinder Type",
    totalQuantity: "Total Quantity",
    distributedQuantity: "Distributed Quantity",
    remainingQuantity: "Remaining Quantity",
    unitPrice: "Unit Price",
    taxRate: "Tax Rate",
    addCylinder: "Add Cylinder",
    updateCylinder: "Update Cylinder",
    deleteCylinder: "Delete Cylinder",
    cylinderAdded: "Cylinder added successfully",
    cylinderUpdated: "Cylinder updated successfully",
    cylinderDeleted: "Cylinder deleted successfully",
    enterCylinderType: "Enter cylinder type",
    enterTotalQuantity: "Enter total quantity",
    enterUnitPrice: "Enter unit price",
    enterTaxRate: "Enter tax rate",
    editInventory: "Edit Inventory",
    noCylinders: "No cylinders in inventory",
  },
  clients: {
    title: "Clients",
    addClient: "Add Client",
    updateClient: "Update Client",
    deleteClient: "Delete Client",
    clientAdded: "Client added successfully",
    clientUpdated: "Client updated successfully",
    clientDeleted: "Client deleted successfully",
    enterClientName: "Enter client name",
    enterClientCode: "Enter client code",
    editClients: "Edit Clients",
    noClients: "No clients added",
  },
  invoices: {
    title: "Invoices",
    invoice: "Invoice",
    client: "Client",
    items: "Items",
    total: "Total",
    automaticDistribution: "Automatic Distribution",
    manualInvoice: "Manual Invoice",
    distributionSettings: "Distribution Settings",
    includeRemainingInventory: "Include Remaining Inventory",
    generateInvoices: "Generate Invoices",
    generating: "Generating...",
    generatedInvoices: "Generated Invoices",
    confirmDistribution: "Confirm Distribution",
    distributionDays: "Distribution Days",
    distributionDaysCount: "Number of distribution days: {{count}}",
    remainingInventory: "Remaining Inventory",
    cylinderType: "Cylinder Type",
    remainingQuantity: "Remaining Quantity",
    value: "Value",
    noClientsError: "Please add clients first",
    noInventoryError: "No inventory available",
    noInvoicesGenerated: "No invoices were generated with the current settings",
    invoicesGeneratedSuccess: "{{count}} invoices generated successfully",
    invoiceGenerationError: "Error generating invoices",
    distributionConfirmed: "Distribution confirmed for {{count}} invoices",
    enterHoliday: "Enter holiday day number",
    addHoliday: "Add",
    excludedHolidays: "Excluded Holidays",
    holidayAdded: "Holiday added successfully",
    holidayRemoved: "Holiday removed",
    holidayAlreadyAdded: "This day is already added as a holiday",
    invalidDay: "Please enter a valid day number between 1-31",
    noDistributionDays: "No distribution days available. Using current date for all invoices.",
  },
};

// Arabic translations
const ar = {
  common: {
    save: "حفظ",
    cancel: "إلغاء",
    edit: "تعديل",
    delete: "حذف",
    name: "الاسم",
    code: "الرمز",
    quantity: "الكمية",
    price: "السعر",
    taxRate: "نسبة الضريبة",
    total: "المجموع",
    january: "يناير",
    february: "فبراير",
    march: "مارس",
    april: "أبريل",
    may: "مايو",
    june: "يونيو",
    july: "يوليو",
    august: "أغسطس",
    september: "سبتمبر",
    october: "أكتوبر",
    november: "نوفمبر",
    december: "ديسمبر",
    year: "السنة",
    month: "الشهر",
    selectMonth: "اختر الشهر",
    selectYear: "اختر السنة",
    distribution: "التوزيع",
    logout: "تسجيل الخروج",
  },
  login: {
    title: "تسجيل الدخول",
    secretCode: "الرمز السري",
    enterCode: "أدخل الرمز السري الخاص بك",
    loginButton: "تسجيل الدخول",
    invalidCode: "رمز سري غير صالح",
  },
  settings: {
    title: "الإعدادات",
    companyName: "اسم الشركة",
    secretCode: "الرمز السري",
    minInvoiceAmount: "أقل مبلغ للفاتورة",
    maxInvoiceAmount: "أعلى مبلغ للفاتورة",
    updateSettings: "تحديث الإعدادات",
    settingsUpdated: "تم تحديث الإعدادات بنجاح",
  },
  inventory: {
    title: "المخزون",
    cylinderType: "نوع الاسطوانة",
    totalQuantity: "الكمية الإجمالية",
    distributedQuantity: "الكمية الموزعة",
    remainingQuantity: "الكمية المتبقية",
    unitPrice: "سعر الوحدة",
    taxRate: "نسبة الضريبة",
    addCylinder: "إضافة اسطوانة",
    updateCylinder: "تحديث اسطوانة",
    deleteCylinder: "حذف اسطوانة",
    cylinderAdded: "تمت إضافة الاسطوانة بنجاح",
    cylinderUpdated: "تم تحديث الاسطوانة بنجاح",
    cylinderDeleted: "تم حذف الاسطوانة بنجاح",
    enterCylinderType: "أدخل نوع الاسطوانة",
    enterTotalQuantity: "أدخل الكمية الإجمالية",
    enterUnitPrice: "أدخل سعر الوحدة",
    enterTaxRate: "أدخل نسبة الضريبة",
    editInventory: "تعديل المخزون",
    noCylinders: "لا يوجد اسطوانات في المخزون",
  },
  clients: {
    title: "العملاء",
    addClient: "إضافة عميل",
    updateClient: "تحديث عميل",
    deleteClient: "حذف عميل",
    clientAdded: "تمت إضافة العميل بنجاح",
    clientUpdated: "تم تحديث العميل بنجاح",
    clientDeleted: "تم حذف العميل بنجاح",
    enterClientName: "أدخل اسم العميل",
    enterClientCode: "أدخل رمز العميل",
    editClients: "تعديل العملاء",
    noClients: "لا يوجد عملاء مضافين",
  },
  invoices: {
    title: "الفواتير",
    invoice: "فاتورة",
    client: "عميل",
    items: "العناصر",
    total: "المجموع",
    automaticDistribution: "توزيع تلقائي",
    manualInvoice: "فاتورة يدوية",
    distributionSettings: "إعدادات التوزيع",
    includeRemainingInventory: "تضمين المخزون المتبقي",
    generateInvoices: "إنشاء الفواتير",
    generating: "جاري الإنشاء...",
    generatedInvoices: "الفواتير التي تم إنشاؤها",
    confirmDistribution: "تأكيد التوزيع",
    distributionDays: "أيام التوزيع",
    distributionDaysCount: "عدد أيام التوزيع: {{count}}",
    remainingInventory: "المخزون المتبقي",
    cylinderType: "نوع الاسطوانة",
    remainingQuantity: "الكمية المتبقية",
    value: "القيمة",
    noClientsError: "الرجاء إضافة عملاء أولاً",
    noInventoryError: "لا يوجد مخزون متاح",
    noInvoicesGenerated: "لم يتم إنشاء أي فواتير بالإعدادات الحالية",
    invoicesGeneratedSuccess: "تم إنشاء {{count}} فواتير بنجاح",
    invoiceGenerationError: "خطأ في إنشاء الفواتير",
    distributionConfirmed: "تم تأكيد التوزيع لـ {{count}} فواتير",
    enterHoliday: "أدخل رقم اليوم العطلة",
    addHoliday: "إضافة",
    excludedHolidays: "الأيام المستثناة",
    holidayAdded: "تمت إضافة العطلة بنجاح",
    holidayRemoved: "تمت إزالة العطلة",
    holidayAlreadyAdded: "هذا اليوم مضاف بالفعل كعطلة",
    invalidDay: "الرجاء إدخال رقم يوم صالح بين 1-31",
    noDistributionDays: "لا توجد أيام توزيع متاحة. استخدام التاريخ الحالي لجميع الفواتير.",
  },
};

// French translations
const fr = {
  common: {
    save: "Enregistrer",
    cancel: "Annuler",
    edit: "Modifier",
    delete: "Supprimer",
    name: "Nom",
    code: "Code",
    quantity: "Quantité",
    price: "Prix",
    taxRate: "Taux de taxe",
    total: "Total",
    january: "Janvier",
    february: "Février",
    march: "Mars",
    april: "Avril",
    may: "Mai",
    june: "Juin",
    july: "Juillet",
    august: "Août",
    september: "Septembre",
    october: "Octobre",
    november: "Novembre",
    december: "Décembre",
    year: "Année",
    month: "Mois",
    selectMonth: "Sélectionner un mois",
    selectYear: "Sélectionner une année",
    distribution: "Distribution",
    logout: "Déconnexion",
  },
  login: {
    title: "Connexion",
    secretCode: "Code Secret",
    enterCode: "Entrez votre code secret",
    loginButton: "Se connecter",
    invalidCode: "Code secret invalide",
  },
  settings: {
    title: "Paramètres",
    companyName: "Nom de l'entreprise",
    secretCode: "Code Secret",
    minInvoiceAmount: "Montant Min. Facture",
    maxInvoiceAmount: "Montant Max. Facture",
    updateSettings: "Mettre à jour les paramètres",
    settingsUpdated: "Paramètres mis à jour avec succès",
  },
  inventory: {
    title: "Inventaire",
    cylinderType: "Type de cylindre",
    totalQuantity: "Quantité totale",
    distributedQuantity: "Quantité distribuée",
    remainingQuantity: "Quantité restante",
    unitPrice: "Prix unitaire",
    taxRate: "Taux de taxe",
    addCylinder: "Ajouter un cylindre",
    updateCylinder: "Mettre à jour le cylindre",
    deleteCylinder: "Supprimer le cylindre",
    cylinderAdded: "Cylindre ajouté avec succès",
    cylinderUpdated: "Cylindre mis à jour avec succès",
    cylinderDeleted: "Cylindre supprimé avec succès",
    enterCylinderType: "Entrez le type de cylindre",
    enterTotalQuantity: "Entrez la quantité totale",
    enterUnitPrice: "Entrez le prix unitaire",
    enterTaxRate: "Entrez le taux de taxe",
    editInventory: "Modifier l'inventaire",
    noCylinders: "Aucun cylindre dans l'inventaire",
  },
  clients: {
    title: "Clients",
    addClient: "Ajouter un client",
    updateClient: "Mettre à jour le client",
    deleteClient: "Supprimer le client",
    clientAdded: "Client ajouté avec succès",
    clientUpdated: "Client mis à jour avec succès",
    clientDeleted: "Client supprimé avec succès",
    enterClientName: "Entrez le nom du client",
    enterClientCode: "Entrez le code du client",
    editClients: "Modifier les clients",
    noClients: "Aucun client ajouté",
  },
  invoices: {
    title: "Factures",
    invoice: "Facture",
    client: "Client",
    items: "Articles",
    total: "Total",
    automaticDistribution: "Distribution Automatique",
    manualInvoice: "Facture Manuelle",
    createManualInvoice: "Créer une Facture Manuelle",
    distributionSettings: "Paramètres de Distribution",
    includeRemainingInventory: "Inclure l'inventaire restant",
    generateInvoices: "Générer des factures",
    generating: "Génération...",
    generatedInvoices: "Factures Générées",
    confirmDistribution: "Confirmer la Distribution",
    distributionDays: "Jours de Distribution",
    distributionDaysCount: "Nombre de jours de distribution: {{count}}",
    remainingInventory: "Inventaire Restant",
    cylinderType: "Type de cylindre",
    remainingQuantity: "Quantité Restante",
    value: "Valeur",
    noClientsError: "Veuillez d'abord ajouter des clients",
    noInventoryError: "Aucun inventaire disponible",
    noInvoicesGenerated: "Aucune facture n'a été générée avec les paramètres actuels",
    invoicesGeneratedSuccess: "{{count}} factures générées avec succès",
    invoiceGenerationError: "Erreur lors de la génération des factures",
    distributionConfirmed: "Distribution confirmée pour {{count}} factures",
    enterHoliday: "Entrez le jour férié",
    addHoliday: "Ajouter",
    excludedHolidays: "Jours fériés exclus",
    holidayAdded: "Jour férié ajouté avec succès",
    holidayRemoved: "Jour férié supprimé",
    holidayAlreadyAdded: "Ce jour est déjà ajouté comme jour férié",
    invalidDay: "Veuillez entrer un numéro de jour valide entre 1 et 31",
    noDistributionDays: "Aucun jour de distribution disponible. Utilisation de la date actuelle pour toutes les factures.",
    selectClient: "Sélectionner un client",
    selectType: "Sélectionner un type",
    available: "disponible",
    unitPrice: "Prix unitaire",
    taxRate: "Taux de taxe",
    addItem: "Ajouter un article",
    description: "Description",
    amount: "Montant",
    subtotal: "Sous-total",
    tax: "Taxe",
    createInvoice: "Créer la facture",
    invalidItemError: "Veuillez sélectionner un type de cylindre et une quantité valide",
    insufficientInventory: "Stock insuffisant pour cette quantité",
    addItems: "Veuillez ajouter au moins un article",
    clientNotFound: "Client non trouvé",
    invoiceCreated: "Facture créée avec succès",
    invalidStartingNumber: "Numéro de départ invalide"
  },
};
